InventoryManagement.Web/Controllers/CarController.cs
using InventoryManagement.Library.Resources;
using InventoryManagement.Library.Services;
using InventoryManagement.Web.Extensions;
using InventoryManagement.Web.Helpers;
using InventoryManagement.Web.Models;
using InventoryManagementLibrary.Helpers;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using InventoryManagement.Core.Entities;

namespace InventoryManagement.Web.Controllers
{
    [Authorize]
    public class CarController : Controller
    {
        // GET: Car
        #region Members

        ICarService _carService;

        #endregion

        #region Constructor

        public CarController(ICarService carService)
        {
            _carService = carService;
        }

        #endregion

        #region Action Methods

        public ActionResult Index()
        {
            return View();
        }

        public JsonResult GetCarList(JQueryDataTableParams param)
        {
            try
            {
                string sortColumn = null;
                if (!(string.IsNullOrEmpty(param.sColumns)))
                {
                    var columns = param.sColumns.Split(',').ToArray();
                    if (param.iSortCol_0 < columns.Length)
                    {
                        sortColumn = columns[param.iSortCol_0];
                    }
                }
                var cars = _carService.GetCarList(UserDataHelper.LoggedInUserInfo().UserID, param.CurrentPage, param.iDisplayLength, sortColumn, param.sSortDir_0, param.sSearch);
                return Json(new
                {
                    sEcho = param.sEcho,
                    iTotalRecords = cars.Any() ? cars[0].TotalRows : 0,
                    iTotalDisplayRecords = cars.Count(),
                    aaData = cars
                }, JsonRequestBehavior.AllowGet);
            }
            catch(Exception ex)
            {
                Logger.LogError(ex, Message.GeneralError);
            }
            return Json(null);
        }

        public PartialViewResult CarModel(long carId = 0)
        {
            var model = new CarModel();
            try
            {
               
                if (carId > 0)
                {
                    var car = _carService.GetById(carId);
                    model.CarId = car.CarId;
                    model.Brand = car.Brand;
                    model.Model = car.Model;
                    model.Price = car.Price;
                    model.Year = car.Year;
                    model.New = car.New;
                }               
            }
            catch (Exception ex)
            {
                Logger.LogError(ex, Message.GeneralError);
            }
            return PartialView("_CarPartial", model);
        }

        [HttpPost]
        public ActionResult Save(CarModel carModel)
        {
            try
            {
                if (!ModelState.IsValid)
                    return this.FailSaveResult();

                Car car;
                if (carModel.CarId > 0)
                    car = _carService.GetById(carModel.CarId);
                else
                    car = new Car();

                car.Brand = carModel.Brand;
                car.Model = carModel.Model;
                car.Price = carModel.Price;
                car.Year = carModel.Year;
                car.New = carModel.New;
                car.UserId = UserDataHelper.LoggedInUserInfo().UserID;
                _carService.Save(car);
                this.AddSuccessMessage("Car saved successfully.");
                return this.SuccessSaveResult();
            }
            catch(Exception ex)
            {
                Logger.LogError(ex, Message.GeneralError);
                ModelState.AddModelError(string.Empty, "Something is wrong! Please try again later");
                return this.FailSaveResult();
            }
        }

        [HttpPost]
        public JsonResult Delete(long carId)
        {
            try
            {
                var car = _carService.GetById(carId);
                if (car == null)
                {
                    this.AddErrorMessage("Car does not exists or deleted.");
                    return this.FailSaveResult();
                }
                _carService.Delete(car);
                this.AddSuccessMessage("Car deleted successfully.");
                return this.SuccessSaveResult();
            }
            catch(Exception ex)
            {
                Logger.LogError(ex, Message.GeneralError);
                this.AddErrorMessage("Something is wrong! Please try again later");
                return this.FailSaveResult();
            }
        }

        #endregion
    }
}

InventoryManagement.Web/Controllers/UserController.cs
using InventoryManagement.Library.Services;
using InventoryManagement.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using InventoryManagement.Core.Entities;
using InventoryManagement.Web.Extensions;
using InventoryManagementLibrary.Helpers;
using InventoryManagement.Web.Helpers;
using InventoryManagement.Library.Resources;
using InventoryManagement.Library.Enums;

namespace InventoryManagement.Web.Controllers
{
    [Authorize(Roles = "Administrator")]
    public class UserController : Controller
    {
        #region Members

        private IUserService _userService;
        private IRoleService _roleService;

        #endregion

        #region Constructor
        public UserController(IUserService userService, IRoleService roleService)
        {
            _userService = userService;
            _roleService = roleService;
        }

        #endregion

        #region Action Methods
        // GET: User
        public ActionResult Index()
        {
            return View();
        }

        public JsonResult GetUserList(JQueryDataTableParams param)
        {
            try
            {
                string sortColumn = null;
                if (!(string.IsNullOrEmpty(param.sColumns)))
                {
                    var columns = param.sColumns.Split(',').ToArray();
                    if (param.iSortCol_0 < columns.Length)
                    {
                        sortColumn = columns[param.iSortCol_0];
                    }
                }
                var users = _userService.GetUserList(param.CurrentPage, param.iDisplayLength, sortColumn, param.sSortDir_0, param.sSearch);

                return Json(new
                {
                    sEcho = param.sEcho,
                    iTotalRecords = users.Any() ? users[0].TotalRows : 0,
                    iTotalDisplayRecords = users.Count(),
                    aaData = users
                }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                Logger.LogError(ex, Message.GeneralError);
            }
            return Json(null);

        }

        public PartialViewResult UserModel(int userId = 0)
        {
            var model = new UserModel();
            try
            {
                if (userId > 0)
                {
                    var user = _userService.GetById(userId);
                    model.UserId = user.UserId;
                    model.FirstName = user.FirstName;
                    model.LastName = user.LastName;
                    model.Email = user.Email;
                    model.Password = user.Password;
                    model.RoleId = user.RoleId;
                    model.IsActive = user.IsActive;
                    model.MobileNo = user.MobileNo;
                }
                model.Roles = _roleService.GetRoles().Select(x => new DropdownHelper()
                {
                    Text = x.Name,
                    Value = x.RoleId
                });
            }
            catch (Exception ex)
            {
                Logger.LogError(ex, Message.GeneralError);
            }
            return PartialView("_UserPartial", model);

        }

        [HttpPost]
        public ActionResult Save(UserModel model)
        {
            try
            {
                if (!ModelState.IsValid)
                    return this.FailSaveResult();

                User user;
                if (model.UserId > 0)
                    user = _userService.GetById(model.UserId);
                else
                    user = new User();

                var isExists = _userService.CheckUserExists(model.Email, model.UserId);
                if (isExists)
                {
                    ModelState.AddModelError(string.Empty, "User with same email already exists! Please enter different value.");
                    return this.FailSaveResult();
                }
                user.FirstName = model.FirstName;
                user.LastName = model.LastName;
                user.Email = model.Email;
                user.Password = model.Password;
                user.MobileNo = model.MobileNo;
                user.IsActive = model.IsActive;
                user.RoleId = model.RoleId;
                _userService.Save(user);
                this.AddSuccessMessage("User saved successfully.");
                return this.SuccessSaveResult();
            }
            catch (Exception ex)
            {
                Logger.LogError(ex, Message.GeneralError);
                ModelState.AddModelError(string.Empty, "Something is wrong! Please try again later");
                return this.FailSaveResult();
            }
        }

        [HttpPost]
        public JsonResult Delete(int userId)
        {
            try
            {
                var user = _userService.GetById(userId);
                if (user == null)
                {
                    this.AddErrorMessage("User does not exists or deleted.");
                    return this.FailSaveResult();
                }
                _userService.Delete(user);
                this.AddSuccessMessage("User deleted successfully.");
                return this.SuccessSaveResult();
            }
            catch (Exception ex)
            {
                Logger.LogError(ex, Message.GeneralError);
                this.AddErrorMessage("Something is wrong! Please try again later");
                return this.FailSaveResult();
            }
        }

        #endregion
    }
}

InventoryManagement.Web/Views/Shared/PageNotFound.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Error</title>
</head>
<body>
    <hgroup>
        <h1>Error.</h1>
        <h2>Sorry! Requested page is not found.</h2>
    </hgroup>
</body>
</html>

InventoryManagement.Web/Views/Shared/Unauthorized.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Error</title>
</head>
<body>
    <hgroup>
        <h1>Error.</h1>
        <h2>Sorry! you are not authorized to perform this action.</h2>
    </hgroup>
</body>
</html>

InventoryManagement.Web/Views/Shared/_Layout.cshtml
@using InventoryManagement.Library.Resources;
@using InventoryManagement.Library.Enums;

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - @Label.InventoryManagement</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink(Label.InventoryManagement, "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @if (HttpContext.Current.User.Identity.IsAuthenticated)
                    {
                        if (HttpContext.Current.User.IsInRole(RoleEnum.Administrator.ToString()))
                        {
                            <li>@Html.ActionLink(Label.UserManagement, "Index", "User")</li>
                        }
                        <li>@Html.ActionLink(Label.CarManament, "Index", "Car")</li>
                    }
                </ul>
                @if (HttpContext.Current.User.Identity.IsAuthenticated)
                {
                    using (Html.BeginForm("LogOff", "Account", FormMethod.Post, new { id = "logoutForm", @class = "navbar-right" }))
                    {
                        @Html.AntiForgeryToken()

                        <ul class="nav navbar-nav navbar-right">
                            <li>
                                <a href="javascript:void(0)">@("Hello " + User.Identity.Name + "!")</a>
                            </li>
                            <li><a href="javascript:document.getElementById('logoutForm').submit()">Log off</a></li>
                        </ul>
                    }
                }
            </div>
        </div>
    </div>
    <div class="container body-content" style="margin:30px auto;">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - @Label.InventoryManagement</p>
        </footer>
    </div>
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/scripts")
    @Scripts.Render("~/bundles/customjs")
    @RenderSection("scripts", required: false)
</body>
</html>